using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace MOD.Jund.Vegs;

public class Veg : VegBase
{
    //<suite-custom-code-autogenerated>
    protected Veg()
    {
    }

    public Veg(Guid id, string? nameAr = null) : base(id, nameAr)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}