using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace MOD.Jund.Vegs;

public class VegManager : VegManagerBase
{
    //<suite-custom-code-autogenerated>
    public VegManager(IVegRepository vegRepository) : base(vegRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}