using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using MOD.Jund.Permissions;
using MOD.Jund.Vegs;

namespace MOD.Jund.Vegs;

public class VegsAppService : VegsAppServiceBase, IVegsAppService
{
    //<suite-custom-code-autogenerated>
    public VegsAppService(IVegRepository vegRepository, VegManager vegManager) : base(vegRepository, vegManager)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}