using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace MOD.Training.Fruits;

public class Fruit : FruitBase
{
    //<suite-custom-code-autogenerated>
    protected Fruit()
    {
    }

    public Fruit(Guid id, string? nameAr = null) : base(id, nameAr)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}