using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace MOD.Training.Fruits;

public class FruitManager : FruitManagerBase
{
    //<suite-custom-code-autogenerated>
    public FruitManager(IFruitRepository fruitRepository) : base(fruitRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}