using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using MOD.Training.Permissions;
using MOD.Training.Fruits;

namespace MOD.Training.Fruits;

public class FruitsAppService : FruitsAppServiceBase, IFruitsAppService
{
    //<suite-custom-code-autogenerated>
    public FruitsAppService(IFruitRepository fruitRepository, FruitManager fruitManager) : base(fruitRepository, fruitManager)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}